version: "3.9"

services:
  # DATABASE
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: authdb,productdb,orderdb,userdb,chatdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5434:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  #  MICROSERVICES 
  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/authdb
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

  product-service:
    build: ./product-service
    container_name: product-service
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/productdb
    ports:
      - "8002:8002"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/orderdb
    ports:
      - "8003:8003"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/userdb
    ports:
      - "8004:8004"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

  chat-service:
    build: ./chat-service
    container_name: chat-service
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/chatdb
    ports:
      - "8005:8005"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - product-service
      - order-service
    networks:
      - backend
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data:

networks:
  backend:
    driver: bridge
